### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by bztrn** [ARCANEDEV/GeoIP#4]
I'm newbie @ Laravel. I mean I'm not able to edit it for L5 but if you can do it and share it I'll be glad.

**Comment by arcanedev-maroc** [comment]
This package is not ready for production projects and i need to rewrite it (It's been a year now without maintain it). 

But i'm glad to hear that. I'm going to put this in my todos list.

**Comment by bztrn** [comment]
Thank you for your interesting & replying my issue. Lastly, Can you share your email address with me if it is proper for you ? (specially gmail for realtime chat) Really I wanna meet w/ you and maybe I can hand some works I got off you as paid if you're interesting.

**Comment by arcanedev-maroc** [comment]
Yeah no problem : arcanedev.maroc@gmail.com
